apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: default
  labels:
    k8s-app: chronograf
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: chronografport
  selector:
    k8s-app: chronograf
