
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chronograf-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
#    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: chronograf.minikube
    http:
      paths:
        - path: /
          backend:
            serviceName: chronograf
            servicePort: 8888
