apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
  labels:
    k8s-app: elasticsearch
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch
      volumes:
        - name: elasticsearchdata
          flexVolume:
            driver: rook.io/rook
            fsType: ceph
            options:
              fsName: bigfs
              clusterName: rook
              path: elasticsearchdata
#      volumes:
#        - name: elasticsearch-logging
#          persistentVolumeClaim:
#            claimName: eslogging-claim
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false
          name: elasticsearch
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9200
              name: db
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearchdata
