
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: es.minikube
    http:
      paths:
        - path: /
          backend:
            serviceName: elasticsearch
            servicePort: 9200
