
kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-logging
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
