apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: default
  labels:
    k8s-app: elasticsearch
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
