apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frhnginxingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: frhnginx.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: frhnginx
          servicePort: 80
