kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: grafana
  labels:
    k8s-app: grafana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: grafana
  labels:
    k8s-app: grafana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: grafana
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: default
  labels:
    k8s-app: grafana
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: default
  labels:
    k8s-app: grafana
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: grafana
      version: v1
  template:
    metadata:
      labels:
        k8s-app: grafana
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: grafana
      volumes:
        - name: grafanadata
          flexVolume:
            driver: rook.io/rook
            fsType: ceph
            options:
              fsName: bigfs
              clusterName: rook
              path: /grafana
      containers:
#        - image: docker.elastic.co/grafana/kibana-oss:6.1.0
        - image: grafana/grafana
          name: grafana
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 3000
              name: grafanaport
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafanadata
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
  labels:
    k8s-app: grafana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: grafanaport
  selector:
    k8s-app: grafana
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
#    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: grafana.lift
    http:
      paths:
        - path: /
          backend:
            serviceName: grafana
            servicePort: 3000
