apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: default
  labels:
    k8s-app: influxdb
    kubernetes.io/name: "InfluxDB"
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: influxdbport
  selector:
    k8s-app: influxdb
