apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kapacitor
  namespace: default
  labels:
    k8s-app: kapacitor
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kapacitor
      version: v1
  template:
    metadata:
      labels:
        k8s-app: kapacitor
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: kapacitor
      volumes:
        - name: kapacitordata
          glusterfs:
            endpoints: glusterfs-cluster
            path: gv3
            readOnly: false
        - configMap:
            name: kapacitorconfigmap
            items:
             - key: kapacitor.conf
               path: kapacitor.conf
            defaultMode: 0644
#      volumes:
#        - name: elasticsearch-logging
#          persistentVolumeClaim:
#            claimName: eslogging-claim
      containers:
        - image: kapacitor:1.4
          name: kapacitor
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9092
              name: kapacitorport
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/kapacitor
              name: kconfig
            - mountPath: /var/lib/kapacitor
              name: kapacitordata
