apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: default
  labels:
    k8s-app: kibana
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
      version: v1
  template:
    metadata:
      labels:
        k8s-app: kibana
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: kibana
      containers:
#        - image: docker.elastic.co/kibana/kibana-oss:6.1.0
        - image: localhost/kibana-logtrail:6.1.0
          name: kibana
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 5601
              name: kibanaport
              protocol: TCP
          volumeMounts:
            - mountPath: /conf
              name: logtrailconfig
            - mountPath: /scripts
              name: setupsh
      restartPolicy: Always
