
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
#    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: kibana.minikube
    http:
      paths:
        - path: /
          backend:
            serviceName: kibana
            servicePort: 5601
