apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
  labels:
    k8s-app: logstash
    kubernetes.io/name: "Logstash"
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: logstashin
  selector:
    k8s-app: logstash
