apiVersion: v1
kind: ConfigMap
metadata:
  name: logstashyaml-config
data:
  logstash.yml: |-
    ## Default Logstash configuration from logstash-docker.
    ## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-oss.yml
    #
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
