apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: default
  labels:
    k8s-app: telegraf
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: telegraf
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: telegraf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: tgconfig
        configMap:
          defaultMode: 0644
          name: tgconfig
      containers:
      - name: telegraf
        image: telegraf:1.3
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: tgconfig
          mountPath: /etc/telegraf
          readOnly: true
          subPath: telegraf.conf
        - name: docker-socket
          mountPath: /var/run/docker.sock
