apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: default
  labels:
    k8s-app: telegraf
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: telegraf
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: telegraf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: tgconfig
        configMap:
          name: tgconfigmap
          items:
            - key: telegraf.conf
              path: telegraf.conf
      containers:
      - name: telegraf
        image: telegraf:1.5
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: tgconfig
          mountPath: /etc/telegraf
          readOnly: true
        - name: docker-socket
          mountPath: /var/run/docker.sock
