
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weavescope-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: k8s.minikube
    http:
      paths:
        - path: /scope
          backend:
            serviceName: weave-scope-app
            servicePort: 80
