
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weavescope-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: scope.minikube
    http:
      paths:
        - path: /
          backend:
            serviceName: weave-scope-app
            servicePort: 4040
