
# Will only run on node labelled with purpose=mongonode for storage att.
# make sure you did: kubectl label nodes k8snode1 purpose=mongonode
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongodata-storage
          persistentVolumeClaim:
            claimName: mongodata-claim
      containers:
        - name: mongo-container
          image: mongo:3.2
          ports:
            - containerPort: 27017
              name: "mongo-server"
          volumeMounts:
            - mountPath: /data/db
              name: mongodata-storage
      nodeSelector:
        purpose: mongonode

#  volumes:
#  - name: test-volume
#    hostPath:
#      # directory location on host
#      path: /mongodata/data/db
#      # this field is optional
#      type: Directory
